# Generated by Django 4.1.5 on 2023-02-04 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='age',
            new_name='price',
        ),
    ]
